services:
  nginx:
    container_name: nginx
    image: nginx:1.27
    restart: unless-stopped
    env_file: .env
    networks:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/secure/:/etc/nginx/templates/
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/reload.sh:/docker-entrypoint.d/reload.sh

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
    networks:
      - frontend
      - backend

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: npm run docker
    stdin_open: true
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    networks:
      - frontend

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: ./scripts/certbot-entrypoint.sh

networks:
  frontend:
  backend: