services:
  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
    networks:
      - frontend
      - backend

  backend:
    image: state-restorer-backend:latest
    tty: true
    environment:
      PYTHONPATH: .
    networks:
      - frontend
      - backend

  frontend:
    image: state-restorer-frontend:latest
    stdin_open: true
    networks:
      - frontend

networks:
  frontend:
  backend: